### ISSUE TITLE
Add full POST examples of each TAXII Request

### ISSUE THREAD

**Issue by gtback** [TAXIIProject/taxiiproject.github.io#1]
Originally from @MarkDavidson 

* [x] TAXII Discovery Request
* [x] TAXII Inbox Message
* [x] TAXII Poll Request
* [x] TAXII Poll Fulfillment Request
* [x] TAXII Collection Information Request
* [x] TAXII Manage Collection Subscription Request

These should get their own section probably.

**Comment by MarkDavidson** [comment]
Done here: http://taxiiproject.github.io/documentation/sample-use/
